// default package
// Generated 19 abr 2023 22:12:31 by Hibernate Tools 6.1.3.Final

/**
 * Nomina generated by hbm2java
 */
public class Nomina implements java.io.Serializable {

	private Integer id;
	private Personal personal;
	private int mes;
	private double salario;
	private int irpf;

	public Nomina() {
	}

	public Nomina(Personal personal, int mes, double salario, int irpf) {
		this.personal = personal;
		this.mes = mes;
		this.salario = salario;
		this.irpf = irpf;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public int getMes() {
		return this.mes;
	}

	public void setMes(int mes) {
		this.mes = mes;
	}

	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

	public int getIrpf() {
		return this.irpf;
	}

	public void setIrpf(int irpf) {
		this.irpf = irpf;
	}

}
