// default package
// Generated 19 abr 2023 22:12:31 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal implements java.io.Serializable {

	private String dni;
	private String nombre;
	private String direccion;
	private int edad;
	private Set nominas = new HashSet(0);

	public Personal() {
	}

	public Personal(String dni, String nombre, String direccion, int edad) {
		this.dni = dni;
		this.nombre = nombre;
		this.direccion = direccion;
		this.edad = edad;
	}

	public Personal(String dni, String nombre, String direccion, int edad, Set nominas) {
		this.dni = dni;
		this.nombre = nombre;
		this.direccion = direccion;
		this.edad = edad;
		this.nominas = nominas;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public Set getNominas() {
		return this.nominas;
	}

	public void setNominas(Set nominas) {
		this.nominas = nominas;
	}

}
