// default package
// Generated 19 abr 2023 22:12:31 by Hibernate Tools 6.1.3.Final

import java.sql.Date;

/**
 * PublicacionesId generated by hbm2java
 */
public class PublicacionesId implements java.io.Serializable {

	private String contenido;
	private Date fecha;
	private String idioma;
	private String titulo;

	public PublicacionesId() {
	}

	public PublicacionesId(String contenido, Date fecha, String idioma, String titulo) {
		this.contenido = contenido;
		this.fecha = fecha;
		this.idioma = idioma;
		this.titulo = titulo;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getIdioma() {
		return this.idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicacionesId))
			return false;
		PublicacionesId castOther = (PublicacionesId) other;

		return ((this.getContenido() == castOther.getContenido()) || (this.getContenido() != null
				&& castOther.getContenido() != null && this.getContenido().equals(castOther.getContenido())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getIdioma() == castOther.getIdioma()) || (this.getIdioma() != null
						&& castOther.getIdioma() != null && this.getIdioma().equals(castOther.getIdioma())))
				&& ((this.getTitulo() == castOther.getTitulo()) || (this.getTitulo() != null
						&& castOther.getTitulo() != null && this.getTitulo().equals(castOther.getTitulo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getContenido() == null ? 0 : this.getContenido().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getIdioma() == null ? 0 : this.getIdioma().hashCode());
		result = 37 * result + (getTitulo() == null ? 0 : this.getTitulo().hashCode());
		return result;
	}

}
