// default package
// Generated 19 abr 2023 22:12:31 by Hibernate Tools 6.1.3.Final

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones implements java.io.Serializable {

	private PublicacionesId id;

	public Publicaciones() {
	}

	public Publicaciones(PublicacionesId id) {
		this.id = id;
	}

	public PublicacionesId getId() {
		return this.id;
	}

	public void setId(PublicacionesId id) {
		this.id = id;
	}

}
